-- ============================================================================
-- Aether ERP — Tabla `compras` (órdenes de compra a proveedores) + RLS
-- ----------------------------------------------------------------------------
-- Ejecutar en Supabase → SQL Editor DESPUÉS de:
--   • 2026-07-roles-y-rls.sql   (helpers public.mi_empresa() / public.mi_rol())
--   • 2026-07-recibir-compra.sql (la tabla public.productos ya debe existir)
-- Es idempotente.
--
-- MOTIVO: el módulo de Compras (app/compras/page.tsx) guardaba las órdenes SOLO
-- en el estado de React y en localStorage. Al recargar la página, el
-- DashboardProvider descartaba ese estado y recargaba ventas/productos/etc. desde
-- Supabase, pero NUNCA las compras (no había tabla), así que las órdenes
-- "desaparecían". Esta tabla les da persistencia real, aislada por empresa vía
-- RLS (idéntico patrón que `ventas`): el cliente NO envía `empresa_id` obligado —
-- lo rellena el DEFAULT `public.mi_empresa()` y el frontend además lo manda
-- explícito (defensa en profundidad); el `with check` valida que sea la propia.
-- ============================================================================

begin;

create extension if not exists pgcrypto;

-- 1) Tabla compras ----------------------------------------------------------
create table if not exists public.compras (
  id             uuid primary key default gen_random_uuid(),
  -- Folio legible para la UI (OC-0001, OC-0002…). Secuencia global; los huecos
  -- entre empresas son cosméticos y no afectan el aislamiento (RLS filtra filas).
  folio          bigint generated by default as identity,
  -- Tenant dueño de la orden. DEFAULT = empresa del usuario autenticado, así el
  -- frontend puede insertar sin enviarlo y el `with check` de RLS lo valida.
  empresa_id     uuid not null default public.mi_empresa()
                   references public.empresas (id) on delete cascade,
  proveedor      text not null,
  items          text not null,            -- descripción del/los insumo(s)
  unidades       integer not null default 0,
  costo          numeric(14, 2) not null default 0,
  eta            text,                      -- entrega ("Por definir" o fecha)
  estado         text not null default 'Pendiente'
                   check (estado in ('Pendiente', 'Recibido', 'Cancelado')),
  -- Vínculo opcional con el catálogo (solo para trazabilidad; el impacto en
  -- stock lo hace la RPC `recibir_compra` al recibir la orden).
  producto_id    uuid references public.productos (id) on delete set null,
  codigo_barras  text,
  created_at     timestamptz not null default now()
);

-- Índices para los listados por empresa y por fecha.
create index if not exists compras_empresa_id_idx on public.compras (empresa_id);
create index if not exists compras_created_at_idx on public.compras (created_at desc);

-- 2) RLS: cada empresa solo ve/gestiona sus propias compras ------------------
alter table public.compras enable row level security;

-- Lectura: miembros ven las compras de SU empresa; el super_admin ve todas.
drop policy if exists compras_select_propia on public.compras;
create policy compras_select_propia on public.compras
  for select
  using (empresa_id = public.mi_empresa() or public.mi_rol() = 'super_admin');

-- Inserción: solo se puede crear una compra para la PROPIA empresa. Como
-- `empresa_id` tiene DEFAULT mi_empresa(), funciona con o sin envío explícito.
drop policy if exists compras_insert_propia on public.compras;
create policy compras_insert_propia on public.compras
  for insert
  with check (empresa_id = public.mi_empresa());

commit;

-- Verificación rápida (debería listar solo las compras de tu empresa):
--   select folio, proveedor, items, unidades, costo, estado, created_at
--   from public.compras order by created_at desc;
